// src/utils/pdf.js
const PDFDocument = require('pdfkit');

function formatDateLocal(v) {
  if (!v) return '—';
  const d = new Date(v);
  if (isNaN(d)) return String(v);
  return d.toLocaleString();
}

/**
 * generateDonationCertificate(donor, collection, tests, overallStatus, nextEligibleDate)
 * returns Promise<Buffer>
 */
function generateDonationCertificate(donor = {}, collection = {}, tests = {}, overallStatus = 'Passed', nextEligibleDate = null) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const bufs = [];
      doc.on('data', (d) => bufs.push(d));
      doc.on('end', () => resolve(Buffer.concat(bufs)));

      // Header
      doc.fontSize(20).text('Donation Certificate', { align: 'center' });
      doc.moveDown(0.5);

      // Meta
      doc.fontSize(10).text(`Certificate ID: CERT-${collection.collection_id || 'N/A'}`, { align: 'right' });
      doc.moveDown();

      // Donor details
      doc.fontSize(12).text(`Donor: ${donor.donor_name || '-'}`);
      doc.text(`Donor ID: ${donor.donor_id || '-'}`);
      if (donor.email) doc.text(`Email: ${donor.email}`);
      doc.moveDown(0.5);

      // Donation details
      const colDate = formatDateLocal(collection.collection_date);
      doc.text(`Donation Date: ${colDate}`);
      doc.text(`Collection ID: ${collection.collection_id || '-'}`);
      if (collection.centre_id) doc.text(`Centre ID: ${collection.centre_id}`);
      if (collection.camp_id) doc.text(`Camp ID: ${collection.camp_id}`);
      if (collection.bag_size) doc.text(`Bag size: ${collection.bag_size}`);
      if (collection.collected_amount) doc.text(`Collected amount: ${collection.collected_amount}`);
      if (collection.lot_number) doc.text(`Lot number: ${collection.lot_number}`);
      doc.moveDown();

      // Test results
      doc.fontSize(12).text('Test Results', { underline: true });
      doc.moveDown(0.2);
      const testsList = [
        ['HIV', tests.hiv || 'Pending'],
        ['HBsAg', tests.hbsag || 'Pending'],
        ['HCV', tests.hcv || 'Pending'],
        ['Syphilis', tests.syphilis || 'Pending'],
        ['Malaria', tests.malaria || 'Pending'],
      ];
      testsList.forEach(([label, value]) => {
        doc.font('Helvetica-Bold').text(label, { continued: true, width: 150 });
        doc.font('Helvetica').text(`: ${value}`);
      });

      doc.moveDown();
      doc.fontSize(12).text(`Overall status: ${overallStatus}`);
      if (overallStatus === 'Passed' && nextEligibleDate) {
        doc.text(`Next eligible donation date: ${nextEligibleDate}`);
      }
      doc.moveDown(1);

      doc.fontSize(10).text('This certificate is generated by the Blood Bank system.', { align: 'left' });
      doc.moveDown(2);
      doc.text('Authorized signatory', { align: 'right' });
      doc.moveDown(0.5);
      doc.text('____________________', { align: 'right' });
      doc.moveDown();

      doc.fontSize(8).fillColor('gray').text('This certificate is for donor records only. For medical advice refer to a registered practitioner.', { align: 'left' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateDonationCertificate };
